import type { Metadata } from "next";
import { Plus_Jakarta_Sans, Fraunces } from "next/font/google";
import Navbar from "@/components/Navbar";
import "./globals.css";

const jakartaSans = Plus_Jakarta_Sans({
  variable: "--font-plus-jakarta-sans",
  subsets: ["latin"],
  display:"swap"
});
const fraunces = Fraunces({
  variable: "--font-fraunces",
  subsets: ["latin"],
  display:"swap"
});

export const metadata: Metadata = {
  title: "Yuri Ferdinand",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${fraunces.variable} ${jakartaSans.variable}`}>
      <body
        className={`text-[#4A443F] antialiased container mx-auto px-4 font-body bg-[#fffdf7]`}
      >
     <Navbar />
        <div className="pt-5">
          {children}
        </div>
      </body>
    </html>
  );
}
