import type { Metadata } from "next";
import { Geist, Cormorant_Garamond } from "next/font/google";
import CursorWrapper from "@/components/ui/cursor-wrapper";
import Navbar from "@/components/Navbar";
import "./globals.css";
import AOSProvider from "@/components/AOSProvider";

const jakartaSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  display:"swap"
});
const cormorantGaramond = Cormorant_Garamond({
  variable: "--font-cormorant-garamond",
  subsets: ["latin"],
  display:"swap"
});

export const metadata: Metadata = {
  title: "Yuri Ferdinand",
  description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{children: React.ReactNode;}>) {
  return (
    <html lang="en" className={`${cormorantGaramond.variable} ${jakartaSans.variable}`}>
      <body
        className={`text-[#e8e6e0] antialiased container mx-auto font-body bg-[#0f0f0f]`}
      >
      <AOSProvider>
        <Navbar />
        <CursorWrapper />
        <div>
          {children}
        </div>
        <hr className="relative left-1/2 right-1/2 -ml-[50vw] -mr-[50vw] border-t-[#2a2a2a] border-t-2" />
        <footer className="text-center text-[#707070] h-13 flex justify-center items-center">
          @2026 Yuri Ferdinand - All Right Reserved
        </footer>
      </AOSProvider>
      </body>
    </html>
  );
}
